version: '3.7'

services:
  obstor1:
    image: ghcr.io/cloudment/obstor
    hostname: obstor1
    volumes:
      - obstor1-data:/export
    ports:
      - "9001:9000"
    networks:
      - obstor_distributed
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      placement:
        constraints:
          - node.labels.obstor1==true
    command: server http://obstor{1...4}/export
    secrets:
      - secret_key
      - access_key
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/obstor/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  obstor2:
    image: ghcr.io/cloudment/obstor
    hostname: obstor2
    volumes:
      - obstor2-data:/export
    ports:
      - "9002:9000"
    networks:
      - obstor_distributed
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      placement:
        constraints:
          - node.labels.obstor2==true
    command: server http://obstor{1...4}/export
    secrets:
      - secret_key
      - access_key
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/obstor/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  obstor3:
    image: ghcr.io/cloudment/obstor
    hostname: obstor3
    volumes:
      - obstor3-data:/export
    ports:
      - "9003:9000"
    networks:
      - obstor_distributed
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      placement:
        constraints:
          - node.labels.obstor3==true
    command: server http://obstor{1...4}/export
    secrets:
      - secret_key
      - access_key
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/obstor/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  obstor4:
    image: ghcr.io/cloudment/obstor
    hostname: obstor4
    volumes:
      - obstor4-data:/export
    ports:
      - "9004:9000"
    networks:
      - obstor_distributed
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      placement:
        constraints:
          - node.labels.obstor4==true
    command: server http://obstor{1...4}/export
    secrets:
      - secret_key
      - access_key
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/obstor/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  obstor1-data:

  obstor2-data:

  obstor3-data:

  obstor4-data:

networks:
  obstor_distributed:
    driver: overlay

secrets:
  secret_key:
    external: true
  access_key:
    external: true
